# DDL도 가급적이면 관리해주는게 좋다고 한다.
# 실제 개발 운영시 DB 덤프를 뜬 이후 다시 신규 프로젝트 작성 시 배포하는 경우가 있는데
# 이 경우 DDL로 관리 및 DML로 insert 및 update를 통해 필요한 데이터만 사용하도록 해놓으면
# 불필요한 데이터를 덤프 뜰 필요가 없지 않을까 한다.
# DB : h2 local
# file : ~/test.mv.db
# 'jdbc:h2:tcp://localhost/~/test'으로 접속


/*CASCADE는 외래키 참조하고 있어도 지우는 것으로 알고 있는데, 현재까지 외래키는 ERD에서 명시만 할 뿐 실제로 적용하지 않았으므로 추후에 확인 필요*/
drop table if exists member CASCADE;
/*자동으로 PK 생성 빈값인 경우*/
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);